// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.
var dyno = {
    age: 0,
    hunger: 10,
    sleep: 10,
    joy: 10
};
console.log('Hello service worker');
setInterval(function() {
    dyno.age++;
    console.log('Dyno age: ' + dyno.age);
    if (dyno.age % 10 === 0) {
        if (dyno.age % 60 === 0) {
            sendMessage('birthday', dyno);
        } else {
            sendMessage('status', dyno);
        }
    }
}, 60000);

function sendMessage(type, dyno) {
    self.clients.matchAll().then(all => all.map(client => client.postMessage({type: 'birthday', dyno: dyno})));
}